// Generated by argus_skill.release_tools.generate_manifest. Do not edit.
export const RELEASE_ID = "0.1.1+fd9a672d69fcad04";
export const RELEASE_SOURCE_DIGEST = "fd9a672d69fcad041031723a3186e4c05dbf13d58a7087c35c9755496a0c39c6";
