// Generated by argus_skill.release_tools.generate_manifest. Do not edit.
export const RELEASE_ID = "0.1.1+7168c767d8b4375d";
export const RELEASE_SOURCE_DIGEST = "7168c767d8b4375d4c90de8d9b2c90b9c58597108b4f3fe66d8f6b6af1232626";
