// Generated by argus_skill.release_tools.generate_manifest. Do not edit.
export const RELEASE_ID = "0.1.1+9dbd2d6a76c50253";
export const RELEASE_SOURCE_DIGEST = "9dbd2d6a76c502531981c278fce61237f91fc443bbd862a295c8d4684b437d75";
